from datetime import datetime
from dateutil import parser
import pytz

data = {
    "action": "opened",
    "number": 1,
    "pull_request": {
        "url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls/1",
        "id": 2638073880,
        "node_id": "PR_kwDOPFnKfM6dPdAY",
        "html_url": "https://github.com/Chavan-Soham/github-action-repo/pull/1",
        "diff_url": "https://github.com/Chavan-Soham/github-action-repo/pull/1.diff",
        "patch_url": "https://github.com/Chavan-Soham/github-action-repo/pull/1.patch",
        "issue_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/1",
        "number": 1,
        "state": "open",
        "locked": False,
        "title": "Test PR webhook",
        "user": {
            "login": "Chavan-Soham",
            "id": 123734164,
            "node_id": "U_kgDOB2AIlA",
            "avatar_url": "https://avatars.githubusercontent.com/u/123734164?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Chavan-Soham",
            "html_url": "https://github.com/Chavan-Soham",
            "followers_url": "https://api.github.com/users/Chavan-Soham/followers",
            "following_url": "https://api.github.com/users/Chavan-Soham/following{/other_user}",
            "gists_url": "https://api.github.com/users/Chavan-Soham/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Chavan-Soham/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Chavan-Soham/subscriptions",
            "organizations_url": "https://api.github.com/users/Chavan-Soham/orgs",
            "repos_url": "https://api.github.com/users/Chavan-Soham/repos",
            "events_url": "https://api.github.com/users/Chavan-Soham/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Chavan-Soham/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": False
        },
        "body": "this is first test for pull request",
        "created_at": "2025-07-03T10:19:15Z",
        "updated_at": "2025-07-03T10:19:15Z",
        "closed_at": None,
        "merged_at": None,
        "merge_commit_sha": None,
        "assignee": None,
        "assignees": [],
        "requested_reviewers": [],
        "requested_teams": [],
        "labels": [],
        "milestone": None,
        "draft": False,
        "commits_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls/1/commits",
        "review_comments_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls/1/comments",
        "review_comment_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls/comments{/number}",
        "comments_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/1/comments",
        "statuses_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/statuses/31c0ce37b20b25ffa6d831314c685d367590bf41",
        "head": {
            "label": "Chavan-Soham:test-pr-branch",
            "ref": "test-pr-branch",
            "sha": "31c0ce37b20b25ffa6d831314c685d367590bf41",
            "user": {
                "login": "Chavan-Soham",
                "id": 123734164,
                "node_id": "U_kgDOB2AIlA",
                "avatar_url": "https://avatars.githubusercontent.com/u/123734164?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Chavan-Soham",
                "html_url": "https://github.com/Chavan-Soham",
                "followers_url": "https://api.github.com/users/Chavan-Soham/followers",
                "following_url": "https://api.github.com/users/Chavan-Soham/following{/other_user}",
                "gists_url": "https://api.github.com/users/Chavan-Soham/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Chavan-Soham/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Chavan-Soham/subscriptions",
                "organizations_url": "https://api.github.com/users/Chavan-Soham/orgs",
                "repos_url": "https://api.github.com/users/Chavan-Soham/repos",
                "events_url": "https://api.github.com/users/Chavan-Soham/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Chavan-Soham/received_events",
                "type": "User",
                "user_view_type": "public",
                "site_admin": False
            },
            "repo": {
                "id": 1012517500,
                "node_id": "R_kgDOPFnKfA",
                "name": "github-action-repo",
                "full_name": "Chavan-Soham/github-action-repo",
                "private": False,
                "owner": {
                    "login": "Chavan-Soham",
                    "id": 123734164,
                    "node_id": "U_kgDOB2AIlA",
                    "avatar_url": "https://avatars.githubusercontent.com/u/123734164?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Chavan-Soham",
                    "html_url": "https://github.com/Chavan-Soham",
                    "followers_url": "https://api.github.com/users/Chavan-Soham/followers",
                    "following_url": "https://api.github.com/users/Chavan-Soham/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Chavan-Soham/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Chavan-Soham/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Chavan-Soham/subscriptions",
                    "organizations_url": "https://api.github.com/users/Chavan-Soham/orgs",
                    "repos_url": "https://api.github.com/users/Chavan-Soham/repos",
                    "events_url": "https://api.github.com/users/Chavan-Soham/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Chavan-Soham/received_events",
                    "type": "User",
                    "user_view_type": "public",
                    "site_admin": False
                },
                "html_url": "https://github.com/Chavan-Soham/github-action-repo",
                "description": "Webhook demo for GitHub push, pull request and merge events.",
                "fork": False,
                "url": "https://api.github.com/repos/Chavan-Soham/github-action-repo",
                "forks_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/forks",
                "keys_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/collaborators{/collaborator}",   
                "teams_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/teams",
                "hooks_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/hooks",
                "issue_events_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/events{/number}",
                "events_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/events",
                "assignees_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/assignees{/user}",
                "branches_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/branches{/branch}",
                "tags_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/tags",
                "blobs_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/languages",
                "stargazers_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/stargazers",
                "contributors_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/contributors",
                "subscribers_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/subscribers",
                "subscription_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/subscription",
                "commits_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/comments{/number}",       
                "contents_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/contents/{+path}",
                "compare_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/merges",
                "archive_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/downloads",
                "issues_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues{/number}",
                "pulls_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/labels{/name}",
                "releases_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/releases{/id}",
                "deployments_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/deployments",
                "created_at": "2025-07-02T13:01:46Z",
                "updated_at": "2025-07-03T07:23:40Z",
                "pushed_at": "2025-07-03T10:18:13Z",
                "git_url": "git://github.com/Chavan-Soham/github-action-repo.git",
                "ssh_url": "git@github.com:Chavan-Soham/github-action-repo.git",
                "clone_url": "https://github.com/Chavan-Soham/github-action-repo.git",
                "svn_url": "https://github.com/Chavan-Soham/github-action-repo",
                "homepage": None,
                "size": 6,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": None,
                "has_issues": True,
                "has_projects": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": False,
                "has_discussions": False,
                "forks_count": 0,
                "mirror_url": None,
                "archived": False,
                "disabled": False,
                "open_issues_count": 1,
                "license": None,
                "allow_forking": True,
                "is_template": False,
                "web_commit_signoff_required": False,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 1,
                "watchers": 0,
                "default_branch": "master",
                "allow_squash_merge": True,
                "allow_merge_commit": True,
                "allow_rebase_merge": True,
                "allow_auto_merge": False,
                "delete_branch_on_merge": False,
                "allow_update_branch": False,
                "use_squash_pr_title_as_default": False,
                "squash_merge_commit_message": "COMMIT_MESSAGES",
                "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
                "merge_commit_message": "PR_TITLE",
                "merge_commit_title": "MERGE_MESSAGE"
            }
        },
        "base": {
            "label": "Chavan-Soham:master",
            "ref": "master",
            "sha": "c7d616a828d21d175601bb439fd0a858a4729884",
            "user": {
                "login": "Chavan-Soham",
                "id": 123734164,
                "node_id": "U_kgDOB2AIlA",
                "avatar_url": "https://avatars.githubusercontent.com/u/123734164?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Chavan-Soham",
                "html_url": "https://github.com/Chavan-Soham",
                "followers_url": "https://api.github.com/users/Chavan-Soham/followers",
                "following_url": "https://api.github.com/users/Chavan-Soham/following{/other_user}",
                "gists_url": "https://api.github.com/users/Chavan-Soham/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Chavan-Soham/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Chavan-Soham/subscriptions",
                "organizations_url": "https://api.github.com/users/Chavan-Soham/orgs",
                "repos_url": "https://api.github.com/users/Chavan-Soham/repos",
                "events_url": "https://api.github.com/users/Chavan-Soham/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Chavan-Soham/received_events",
                "type": "User",
                "user_view_type": "public",
                "site_admin": False
            },
            "repo": {
                "id": 1012517500,
                "node_id": "R_kgDOPFnKfA",
                "name": "github-action-repo",
                "full_name": "Chavan-Soham/github-action-repo",
                "private": False,
                "owner": {
                    "login": "Chavan-Soham",
                    "id": 123734164,
                    "node_id": "U_kgDOB2AIlA",
                    "avatar_url": "https://avatars.githubusercontent.com/u/123734164?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/Chavan-Soham",
                    "html_url": "https://github.com/Chavan-Soham",
                    "followers_url": "https://api.github.com/users/Chavan-Soham/followers",
                    "following_url": "https://api.github.com/users/Chavan-Soham/following{/other_user}",
                    "gists_url": "https://api.github.com/users/Chavan-Soham/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/Chavan-Soham/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/Chavan-Soham/subscriptions",
                    "organizations_url": "https://api.github.com/users/Chavan-Soham/orgs",
                    "repos_url": "https://api.github.com/users/Chavan-Soham/repos",
                    "events_url": "https://api.github.com/users/Chavan-Soham/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/Chavan-Soham/received_events",
                    "type": "User",
                    "user_view_type": "public",
                    "site_admin": False
                },
                "html_url": "https://github.com/Chavan-Soham/github-action-repo",
                "description": "Webhook demo for GitHub push, pull request and merge events.",
                "fork": False,
                "url": "https://api.github.com/repos/Chavan-Soham/github-action-repo",
                "forks_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/forks",
                "keys_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/keys{/key_id}",
                "collaborators_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/collaborators{/collaborator}",   
                "teams_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/teams",
                "hooks_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/hooks",
                "issue_events_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/events{/number}",
                "events_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/events",
                "assignees_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/assignees{/user}",
                "branches_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/branches{/branch}",
                "tags_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/tags",
                "blobs_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/blobs{/sha}",
                "git_tags_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/tags{/sha}",
                "git_refs_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/refs{/sha}",
                "trees_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/trees{/sha}",
                "statuses_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/statuses/{sha}",
                "languages_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/languages",
                "stargazers_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/stargazers",
                "contributors_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/contributors",
                "subscribers_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/subscribers",
                "subscription_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/subscription",
                "commits_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/commits{/sha}",
                "git_commits_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/commits{/sha}",
                "comments_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/comments{/number}",
                "issue_comment_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/comments{/number}",       
                "contents_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/contents/{+path}",
                "compare_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/compare/{base}...{head}",
                "merges_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/merges",
                "archive_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/{archive_format}{/ref}",
                "downloads_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/downloads",
                "issues_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues{/number}",
                "pulls_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls{/number}",
                "milestones_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/milestones{/number}",
                "notifications_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/notifications{?since,all,participating}",
                "labels_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/labels{/name}",
                "releases_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/releases{/id}",
                "deployments_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/deployments",
                "created_at": "2025-07-02T13:01:46Z",
                "updated_at": "2025-07-03T07:23:40Z",
                "pushed_at": "2025-07-03T10:18:13Z",
                "git_url": "git://github.com/Chavan-Soham/github-action-repo.git",
                "ssh_url": "git@github.com:Chavan-Soham/github-action-repo.git",
                "clone_url": "https://github.com/Chavan-Soham/github-action-repo.git",
                "svn_url": "https://github.com/Chavan-Soham/github-action-repo",
                "homepage": None,
                "size": 6,
                "stargazers_count": 0,
                "watchers_count": 0,
                "language": None,
                "has_issues": True,
                "has_projects": True,
                "has_downloads": True,
                "has_wiki": True,
                "has_pages": False,
                "has_discussions": False,
                "forks_count": 0,
                "mirror_url": None,
                "archived": False,
                "disabled": False,
                "open_issues_count": 1,
                "license": None,
                "allow_forking": True,
                "is_template": False,
                "web_commit_signoff_required": False,
                "topics": [],
                "visibility": "public",
                "forks": 0,
                "open_issues": 1,
                "watchers": 0,
                "default_branch": "master",
                "allow_squash_merge": True,
                "allow_merge_commit": True,
                "allow_rebase_merge": True,
                "allow_auto_merge": False,
                "delete_branch_on_merge": False,
                "allow_update_branch": False,
                "use_squash_pr_title_as_default": False,
                "squash_merge_commit_message": "COMMIT_MESSAGES",
                "squash_merge_commit_title": "COMMIT_OR_PR_TITLE",
                "merge_commit_message": "PR_TITLE",
                "merge_commit_title": "MERGE_MESSAGE"
            }
        },
        "_links": {
            "self": {
                "href": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls/1"
            },
            "html": {
                "href": "https://github.com/Chavan-Soham/github-action-repo/pull/1"
            },
            "issue": {
                "href": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/1"
            },
            "comments": {
                "href": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/1/comments"
            },
            "review_comments": {
                "href": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls/1/comments"
            },
            "review_comment": {
                "href": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls/comments{/number}"
            },
            "commits": {
                "href": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls/1/commits"
            },
            "statuses": {
                "href": "https://api.github.com/repos/Chavan-Soham/github-action-repo/statuses/31c0ce37b20b25ffa6d831314c685d367590bf41"
            }
        },
        "author_association": "OWNER",
        "auto_merge": None,
        "active_lock_reason": None,
        "merged": False,
        "mergeable": None,
        "rebaseable": None,
        "mergeable_state": "unknown",
        "merged_by": None,
        "comments": 0,
        "review_comments": 0,
        "maintainer_can_modify": False,
        "commits": 1,
        "additions": 0,
        "deletions": 0,
        "changed_files": 1
    },
    "repository": {
        "id": 1012517500,
        "node_id": "R_kgDOPFnKfA",
        "name": "github-action-repo",
        "full_name": "Chavan-Soham/github-action-repo",
        "private": False,
        "owner": {
            "login": "Chavan-Soham",
            "id": 123734164,
            "node_id": "U_kgDOB2AIlA",
            "avatar_url": "https://avatars.githubusercontent.com/u/123734164?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Chavan-Soham",
            "html_url": "https://github.com/Chavan-Soham",
            "followers_url": "https://api.github.com/users/Chavan-Soham/followers",
            "following_url": "https://api.github.com/users/Chavan-Soham/following{/other_user}",
            "gists_url": "https://api.github.com/users/Chavan-Soham/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Chavan-Soham/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Chavan-Soham/subscriptions",
            "organizations_url": "https://api.github.com/users/Chavan-Soham/orgs",
            "repos_url": "https://api.github.com/users/Chavan-Soham/repos",
            "events_url": "https://api.github.com/users/Chavan-Soham/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Chavan-Soham/received_events",
            "type": "User",
            "user_view_type": "public",
            "site_admin": False
        },
        "html_url": "https://github.com/Chavan-Soham/github-action-repo",
        "description": "Webhook demo for GitHub push, pull request and merge events.",
        "fork": False,
        "url": "https://api.github.com/repos/Chavan-Soham/github-action-repo",
        "forks_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/forks",
        "keys_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/teams",
        "hooks_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/hooks",
        "issue_events_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/events{/number}",
        "events_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/events",
        "assignees_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/assignees{/user}",
        "branches_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/branches{/branch}",
        "tags_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/tags",
        "blobs_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/languages",
        "stargazers_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/stargazers",
        "contributors_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/contributors",
        "subscribers_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/subscribers",
        "subscription_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/subscription",
        "commits_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/contents/{+path}",
        "compare_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/merges",
        "archive_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/downloads",
        "issues_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/issues{/number}",
        "pulls_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/labels{/name}",
        "releases_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/releases{/id}",
        "deployments_url": "https://api.github.com/repos/Chavan-Soham/github-action-repo/deployments",
        "created_at": "2025-07-02T13:01:46Z",
        "updated_at": "2025-07-03T07:23:40Z",
        "pushed_at": "2025-07-03T10:18:13Z",
        "git_url": "git://github.com/Chavan-Soham/github-action-repo.git",
        "ssh_url": "git@github.com:Chavan-Soham/github-action-repo.git",
        "clone_url": "https://github.com/Chavan-Soham/github-action-repo.git",
        "svn_url": "https://github.com/Chavan-Soham/github-action-repo",
        "homepage": None,
        "size": 6,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": None,
        "has_issues": True,
        "has_projects": True,
        "has_downloads": True,
        "has_wiki": True,
        "has_pages": False,
        "has_discussions": False,
        "forks_count": 0,
        "mirror_url": None,
        "archived": False,
        "disabled": False,
        "open_issues_count": 1,
        "license": None,
        "allow_forking": True,
        "is_template": False,
        "web_commit_signoff_required": False,
        "topics": [],
        "visibility": "public",
        "forks": 0,
        "open_issues": 1,
        "watchers": 0,
        "default_branch": "master"
    },
    "sender": {
        "login": "Chavan-Soham",
        "id": 123734164,
        "node_id": "U_kgDOB2AIlA",
        "avatar_url": "https://avatars.githubusercontent.com/u/123734164?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/Chavan-Soham",
        "html_url": "https://github.com/Chavan-Soham",
        "followers_url": "https://api.github.com/users/Chavan-Soham/followers",
        "following_url": "https://api.github.com/users/Chavan-Soham/following{/other_user}",
        "gists_url": "https://api.github.com/users/Chavan-Soham/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/Chavan-Soham/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/Chavan-Soham/subscriptions",
        "organizations_url": "https://api.github.com/users/Chavan-Soham/orgs",
        "repos_url": "https://api.github.com/users/Chavan-Soham/repos",
        "events_url": "https://api.github.com/users/Chavan-Soham/events{/privacy}",
        "received_events_url": "https://api.github.com/users/Chavan-Soham/received_events",
        "type": "User",
        "user_view_type": "public",
        "site_admin": False
    }
}


""" print(data["pusher"]["name"])
print(data["ref"].split("/")[-1]) """

print("From branch: ", data["pull_request"]["head"]["ref"])
print("to branch: ", data["pull_request"]["base"]["ref"])

""" def get_day_with_suffix(day):
    if 11 <= day <= 13:
        return f"{day}th"
    suffix = {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")
    return f"{day}{suffix}"

# Example GitHub timestamp string from payload
timestamp_str = data["commits"][0]["timestamp"]

# Parse timestamp string
parsed_time = parser.parse(timestamp_str)

# Convert to UTC
utc_time = parsed_time.astimezone(pytz.utc)

# Create final formatted string
day_with_suffix = get_day_with_suffix(utc_time.day)
formatted_time = f"{day_with_suffix} {utc_time.strftime('%B %Y - %I:%M %p')} UTC"

print(formatted_time) """